<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>LightStudio.Ffmpeg.MT.browser-wasm</PackageId>
    <Description>Pthread-enabled static FFmpeg libraries built with Emscripten for the browser-wasm runtime.</Description>
    <PackageTags>ffmpeg;webassembly;wasm;browser-wasm;emscripten;multithreading;pthreads</PackageTags>
    <PackageReadmeFile>README.MT.md</PackageReadmeFile>
    <FFmpegArtifactsPath>$(MSBuildThisFileDirectory)../artifacts/ffmpeg-MT-browser-wasm</FFmpegArtifactsPath>
  </PropertyGroup>

  <Import Project="FFmpeg.browser-wasm.Package.targets" />
</Project>